services:
    sonata.admin.post:
        class: Acme\DemoBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
    sonata.admin.event:
        class: Acme\DemoBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Event" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]